CREATE TABLE IF NOT EXISTS student.mh_historical_weather_hourly (
        time TIMESTAMP PRIMARY KEY,
        date TEXT REFERENCES student.mh_historical_weather_daily(date) ON DELETE CASCADE,
        time_epoch INTEGER NOT NULL,
        temp_c FLOAT,
        temp_f FLOAT,
        is_day INTEGER,
        condition_text TEXT,
        condition_icon TEXT,
        condition_code INTEGER,
        wind_mph FLOAT,
        wind_kph FLOAT,
        wind_degree INTEGER,
        wind_dir TEXT,
        pressure_mb FLOAT,
        pressure_in FLOAT,
        precip_mm FLOAT,
        precip_in FLOAT,
        snow_cm FLOAT,
        humidity INTEGER,
        cloud INTEGER,
        feelslike_c FLOAT,
        feelslike_f FLOAT,
        windchill_c FLOAT,
        windchill_f FLOAT,
        heatindex_c FLOAT,
        heatindex_f FLOAT,
        dewpoint_c FLOAT,
        dewpoint_f FLOAT,
        will_it_rain INTEGER,
        chance_of_rain INTEGER,
        will_it_snow INTEGER,
        chance_of_snow INTEGER,
        vis_km FLOAT,
        vis_miles FLOAT,
        gust_mph FLOAT,
        gust_kph FLOAT,
        uv FLOAT
    );