CREATE TABLE IF NOT EXISTS student.current_weather_mh_de11 (
        id SERIAL PRIMARY KEY,
        location_name TEXT NOT NULL,
        region TEXT,
        country TEXT,
        latitude FLOAT,
        longitude FLOAT,
        local_time TIMESTAMP,
        temp_c FLOAT,
        temp_f FLOAT,
        condition TEXT,
        wind_mph FLOAT,
        wind_kph FLOAT,
        wind_degree INT,
        wind_dir TEXT,
        pressure_mb FLOAT,
        humidity INT,
        cloud INT,
        feelslike_c FLOAT,
        feelslike_f FLOAT,
        air_quality_co FLOAT,
        air_quality_no2 FLOAT,
        air_quality_o3 FLOAT,
        air_quality_so2 FLOAT,
        air_quality_pm2_5 FLOAT,
        air_quality_pm10 FLOAT,
        air_quality_us_epa_index INT,
        air_quality_gb_defra_index INT,
        UNIQUE(location_name, local_time)  -- Prevents duplicate weather entries for same location & time
    );