CREATE TABLE IF NOT EXISTS student.mh_historical_weather_daily (
        date TEXT PRIMARY KEY,
        location_name TEXT,
        location_region TEXT,
        location_country TEXT,
        location_lat FLOAT,
        location_lon FLOAT,
        location_tz_id TEXT,
        location_localtime TEXT,
        date_epoch INTEGER NOT NULL,
        maxtemp_c FLOAT,
        maxtemp_f FLOAT,
        mintemp_c FLOAT,
        mintemp_f FLOAT,
        avgtemp_c FLOAT,
        avgtemp_f FLOAT,
        maxwind_mph FLOAT,
        maxwind_kph FLOAT,
        totalprecip_mm FLOAT,
        totalprecip_in FLOAT,
        totalsnow_cm FLOAT,
        avgvis_km FLOAT,
        avgvis_miles FLOAT,
        avghumidity INTEGER,
        daily_will_it_rain INTEGER,
        daily_chance_of_rain INTEGER,
        daily_will_it_snow INTEGER,
        daily_chance_of_snow INTEGER,
        condition_text TEXT,
        condition_icon TEXT,
        condition_code INTEGER,
        uv FLOAT,
        sunrise TEXT,
        sunset TEXT,
        moonrise TEXT,
        moonset TEXT,
        moon_phase TEXT,
        moon_illumination INTEGER
    );